In [44]:
'''
Name: Shashwat Ghevde
'''

'\nName: Shashwat Ghevde\n'

In [45]:
import pandas as pd
import os

In [46]:
# accessing the tickers.txt in Task 1 folder

parent_dir = ".."
task_dir = "task_1"
filename = "tickers.txt"

data_directory = os.path.join(parent_dir, task_dir,filename)

tickers = []
with open(data_directory, 'r') as f:
    for line in f:
        tickers.append(line.strip())

In [48]:
'''
Parameters: df(Dataframe with the wanted columns), ticker(String with company ticker name)
Return: N/A

This method calculates the price momentum

issue: had to re-learn lambda functions to account for Stock Splits = 0(ZeroDivisionError)
'''

def calculate_price_momentum(df, ticker):
    df[f"{ticker}"] = ((df["Close"] - df["Close"].shift(5)) / df["Close"].shift(5)) * 100
    return df

# Initializing DataFrame for putting information into csv
momentum_df = pd.DataFrame()

parent_dir = ".."
task_dir = "task_1"
data_dir = "data"
extension = ".csv"

first_ticker_flag = True

# Used to append Momentum to the Dataframe
for ticker in tickers:
    
    ticker_extension = ticker + extension
    
    # reading the data into the CSV
    company_path = os.path.join(parent_dir, task_dir, data_dir, ticker_extension)
    df = pd.read_csv(company_path)
    
    
    df = calculate_momentum(df, ticker)    
    df = df[['Date', f'{ticker}']]
    
    # issue: adding the price momentum because it kept getting reassigned
    
    # if there is only one company, add the dataframe, and turn off the flag
    if first_ticker_flag:
        momentum_df = df
        first_ticker_flag = False
    else:
        #else, merge on the new company to the dataframe
        momentum_df = pd.merge(momentum_df, df, on = "Date", how = "left")
        
# replacing NaN with Spaces
momentum_df.fillna('', inplace = True)



# adding to price_momentum.csv
filename = "price_momentum.csv"
momentum_df.to_csv(filename)


momentum_df

,Date,MSFT,AAPL,NVDA,AMZN,GOOGL,META,GOOG,CVX,TSLA,...,JNJ,HD,MA,PG,COST,MRK,ABBV,ADBE,CRM,AMD
0,01/04/2021,,,,,,,,,,...,,,,,,,,,,
1,01/05/2021,,,,,,,,,,...,,,,,,,,,,
2,01/06/2021,,,,,,,,,,...,,,,,,,,,,
3,01/07/2021,,,,,,,,,,...,,,,,,,,,,
4,01/08/2021,,,,,,,,,,...,,,,,,,,,,
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
748,12/22/2023,1.038484,-2.009412,-0.122726,2.300458,6.704373,5.51475,6.634792,1.138264,-0.378701,...,0.193351,-1.52825,1.321166,0.916915,1.939819,2.464082,0.584272,2.406446,1.811923,0.323401
749,12/26/2023,0.539387,-1.449785,-1.593542,-0.428379,4.212077,2.962681,4.103801,1.823898,1.797042,...,0.450333,-0.427582,-0.179053,-0.157344,-0.971759,1.499431,0.782167,-0.14521,0.997764,3.246947
750,12/27/2023,0.217006,-1.924452,-0.376985,-0.292605,2.722284,2.132093,2.418535,0.178056,1.640619,...,-0.070306,-1.005484,-0.260893,-0.075247,0.623147,1.399198,0.833331,-1.415718,0.900357,4.224055
751,12/28/2023,1.257352,-0.641588,2.932805,0.8283,1.366199,2.588184,1.159956,-0.319465,2.443956,...,2.159586,-0.372861,1.63786,1.264669,2.598954,3.236519,2.017269,-0.090591,2.048026,9.810285
752,12/29/2023,0.669266,-1.10437,1.085937,-1.235045,-0.519866,-0.036715,-0.613548,-1.028467,-2.365424,...,1.227079,-0.693473,0.725011,1.580476,1.492947,2.472034,1.55973,-0.589869,-1.53788,5.360589